ユーザー編集画面でプロフ画像変更　Feature/#90 profile pic add2
hayaminahiro/family_online_visit pull request #92
Opened 2020-10-24 13:54 UTC by yuya0311

## Issueへのリンク
・https://github.com/hayaminahiro/family_online_visit/issues/90

## 実装内容
・ユーザー編集からプロフ画像を変更

## やらないこと
・なし

## できるようになること（ユーザ目線）
・プロフ画像の変更

## できなくなること（ユーザ目線）
・なし

## 動作確認
・ユーザー編集画面で変更→他画面で実際に変更した画像が表示されるか確認

## その他
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

## 画像

2020-10-25 02:45 UTC, hayaminahiro commented on app/views/users/show.html.erb
>              <%= image_tag 'user_default.png', class: "user-profile-image" %>
S3へ移行お願いしますm(_ _)m

2020-10-25 02:49 UTC, hayaminahiro commented on app/views/users/show.html.erb
> +          <% if current_user.image.present? %>
現在プルリクを出しているお知らせ画像、または施設アイコンの方に、動く同じパターンのヘルパーメソッドを上げていますので参考にして下さい。ユーザーヘルパーに記載した方が良いと思います＾＾

2020-10-25 02:59 UTC, hayaminahiro requested changes
【マイページの画像】
・アイコンなので、丸型にした方が良いと思いました。
【設定編集ページ】
・現在どの画像に設定されているか分からないので現在の画像表示と画像プレビュー
・画像削除機能
・ドロップボックス(スペースの問題で必要かは要検討)
・エラーrender時に設定していた画像が消えてしまうので、キャッシュ機能の搭載
これらが必要だと思われますが、ご検討お願い致しますm(_ _)m
【ログインページ】
・エラーrender時のエラーメッセージが表示されません。もしかしたら前回のタスク時にコードが消えてしまった可能性もあるので、一緒に見て頂いても宜しいですか？

2020-10-25 05:24 UTC, hayaminahiro commented on app/models/user.rb
> +
このあたりの改行は一つあれば良いと思いました。

2020-10-25 05:28 UTC, hayaminahiro commented on app/views/users/registrations/edit.html.erb
> +                <td><%= f.file_field :image %></td>
・現在どの画像に設定されているか分からないので現在の画像表示と画像プレビュー
・画像削除機能
・ドロップボックス(スペースの問題で必要かは要検討)
・エラーrender時に設定していた画像が消えてしまうので、キャッシュ機能の搭載
これらが必要だと思われますが、ご検討お願い致しますm(_ _)m

2020-10-25 09:17 UTC, yuya0311 commented on app/views/users/show.html.erb
> +            <%= image_tag current_user.image.url, class: "profile-image" %>
完了致しました。
リンク貼り付けありがとうございました。
<img width="1361" alt="スクリーンショット 2020-10-25 18 14 57" src="https://user-images.githubusercontent.com/64314961/97103144-0a8d6c00-16ee-11eb-84ce-bf2189ef1132.png">
<img width="1361" alt="スクリーンショット 2020-10-25 18 16 05" src="https://user-images.githubusercontent.com/64314961/97103182-36105680-16ee-11eb-8a30-99bef0acbf02.png">

2020-10-25 09:17 UTC, yuya0311 commented on app/views/users/show.html.erb
>              <%= image_tag 'user_default.png', class: "user-profile-image" %>
完了致しました。

2020-10-25 09:17 UTC, yuya0311 commented on app/views/users/show.html.erb
> +          <% if current_user.image.present? %>
完了致しました。
齋藤さんのコードを参考にさせて頂きました。

2020-10-25 09:18 UTC, yuya0311 commented on app/models/user.rb
> +
修正致しました。

2020-10-30 05:16 UTC, yuya0311 commented on app/assets/stylesheets/facilities.scss
> +input#icon_edit_delete[type="checkbox"] + label.check_position:before {
ご指摘ありがとうございます。見逃してました。削除いたしました。

2020-10-30 05:26 UTC, yuya0311 commented on app/views/signup/step3.html.erb
> +<section class="">
削除いたしました。

2020-10-30 05:27 UTC, yuya0311 commented on app/views/users/shared/_links.html.erb
> +        </button>
調整いたしました。

2020-10-30 07:03 UTC, yuya0311 commented on app/views/users/sessions/new.html.erb
> +            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
変更致しました！

2020-10-30 07:04 UTC, yuya0311 commented on app/views/signup/step2.html.erb
> +<section class="">
削除いたしました。

2020-10-30 07:04 UTC, yuya0311 commented on app/views/signup/step1.html.erb
> +<section class="">
削除いたしました。

2020-10-30 07:08 UTC, yuya0311 commented on app/views/users/show.html.erb
>      <nav class="">
削除いたしました。

2020-10-30 13:08 UTC, hayaminahiro commented on app/assets/stylesheets/static_pages.scss
> +  background-image: url('/signup-pic2.jpg');
S3移行お願いします🙇‍♂️

2020-10-30 13:14 UTC, hayaminahiro commented on app/views/signup/step2.html.erb
> +      <div class="content has-text-centered">
このページは全体的に、数カ所インデントが崩れてしまっているので、見直して見て下さい🙇‍♂️

2020-10-30 13:15 UTC, hayaminahiro commented on app/views/signup/step2.html.erb
空けても１行で良いと思います🙂

2020-10-30 13:16 UTC, hayaminahiro commented on app/views/signup/step2.html.erb
>  <script>
このscriptタグの中も奥にインデント入れて下さい🙇‍♂️

2020-10-30 13:21 UTC, hayaminahiro commented on app/views/signup/step3.html.erb
> +          <div class="confirm-newuser"><%= session[:name] %>
ここから下全部、<div class="confirm-newuser"><%= session[:name] %></div>
または
<div class="confirm-newuser">
  <%= session[:name] %>
</div>
など、揃えた方が良いかと思います🙂

2020-10-30 13:22 UTC, hayaminahiro commented on app/views/signup/step3.html.erb
> +          <div class="confirm-newuser"><%= session[:name] %>
ここから下全部、divタグの位置を揃えた方が良いかと思います🙂

2020-10-30 15:05 UTC, hayaminahiro commented on app/views/users/registrations/edit.html.erb
> +                    <%= user_icon_edit(@user) %>
画像が歪んでいます。マイページの方は大丈夫なので、CSSを統一した方が良いと思います🙇‍♂️

2020-10-30 15:07 UTC, hayaminahiro commented on app/views/users/registrations/edit.html.erb
> +                <%= f.file_field :image, id: :user_img %>
ドラッグ&ドロップは実装しない方向でいきますか？

2020-11-01 11:26 UTC, yuya0311 commented on app/views/users/registrations/edit.html.erb
> +                    <%= user_icon_edit(@user) %>
ご指摘ありがとうございます。
画像が歪んでいるというのは、どういう事でしょうか？
私の方では、歪んでいるようには見えなくて。。
ちなみにここの部分は、初めては同じcssにしたんですが、同じだと、どうしても四角の図になってしまったので、cssを分けました。。
<img width="1440" alt="スクリーンショット 2020-11-01 20 18 25" src="https://user-images.githubusercontent.com/64314961/97801442-23fb5e80-1c80-11eb-84f0-1f509a6ce5d3.png">

2020-11-01 11:27 UTC, yuya0311 commented on app/assets/stylesheets/static_pages.scss
> +  background-image: url('/signup-pic2.jpg');
移行完了致しました。

2020-11-01 11:27 UTC, yuya0311 commented on app/views/signup/step2.html.erb
> +      <div class="content has-text-centered">
見直し完了致しました。

2020-11-01 11:27 UTC, yuya0311 commented on app/views/signup/step2.html.erb
一行のみ開けました。

2020-11-01 11:28 UTC, yuya0311 commented on app/views/signup/step2.html.erb
>  <script>
変更致しました。

2020-11-01 11:28 UTC, yuya0311 commented on app/views/signup/step3.html.erb
> +          <div class="confirm-newuser"><%= session[:name] %>
変更致しました。

2020-11-06 15:28 UTC, hayaminahiro requested changes
users/registrations/edit.html.erb の9行目が<p class="edit-link">施設</phas-text-weight-bold>になっているので、<p class="edit-link">施設</p>に修正お願い出来ますか？

2020-11-06 15:30 UTC, hayaminahiro commented
> users/registrations/edit.html.erb の9行目が
> 
> 施設になっているので、
> 
> 施設
> 
> に修正お願い出来ますか？

2020-11-06 15:36 UTC, hayaminahiro commented on app/views/users/registrations/edit.html.erb
>                  <td>千葉県佐倉市００−００</td>
このページusers/registrations/edit.html.erb の9行目が<p class="edit-link">施設</phas-text-weight-bold>になっているので、<p class="edit-link">施設</p>に変更出来ますか？

2020-11-06 15:44 UTC, hayaminahiro commented on app/views/users/registrations/edit.html.erb
> +                  <div class="user-icon-edits">
user-icon-edits このcssは使ってないですか？

2020-11-08 12:12 UTC, yuya0311 commented on app/views/users/registrations/edit.html.erb
> +                  <div class="user-icon-edits">
はい。削除いたしました。

2020-11-10 11:30 UTC, merged